name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true
    - uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: yarn install, build and deploy
      run: |
        yarn
        yarn build
        npx now public --prod --token ${{ secrets.ZEIT_TOKEN }}